#!/bin/bash -eu

### create virtual environment for daily harvesting of surveys for CATCH
test ! -e .venv && python3 -m venv .venv --prompt='catch-v1'
source .venv/bin/activate
python3 -m pip install -U pip setuptools wheel

pushd .
mkdir -p build
cd build

# checkout code, S2 and Abseil
S2_TAG=v0.10.0
test ! -e ${S2_TAG}.tar.gz && wget https://github.com/google/s2geometry/archive/refs/tags/${S2_TAG}.tar.gz
test ! -e s2geometry-${S2_TAG} && tar xzf ${S2_TAG}.tar.gz

# install abseil from source, as per s2geometry's readme
# (it must be configured with -DCMAKE_POSITION_INDEPENDENT_CODE=ON)
# We are using C++11, and the last version to support it is LTS 20220623.1
ABSEIL_TAG=20220623.1
test ! -e ${ABSEIL_TAG}.tar.gz && wget https://github.com/abseil/abseil-cpp/archive/refs/tags/${ABSEIL_TAG}.tar.gz
test ! -e abseil-cpp-${ABSEIL_TAG} && tar xzf ${ABSEIL_TAG}.tar.gz

cd abseil-cpp-${ABSEIL_TAG}
mkdir -p build
cd build
cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_CXX_STANDARD=11 -DCMAKE_INSTALL_PREFIX=$VIRTUAL_ENV -DABSL_PROPAGATE_CXX_STD=ON ..
make -j $(nproc)
make install
cd ../..
export LDFLAGS="-L$VIRTUAL_ENV/lib -Wl,-rpath=$VIRTUAL_ENV/lib"

cd s2geometry-${S2_TAG:1}
ln -sfn ../abseil-cpp-${ABSEIL_TAG} abseil
mkdir -p build
cd build
cmake -DCMAKE_PREFIX_PATH=$VIRTUAL_ENV -DCMAKE_CXX_STANDARD=11 -DCMAKE_INSTALL_PREFIX=$VIRTUAL_ENV -Wno-dev ..
make -j $(nproc)
make install

popd

# install python libraries
pip install numpy sbpy cython psycopg2-binary
pip install -e git+https://git@github.com/Small-Bodies-Node/sbsearch.git#egg=sbsearch
pip install -e .
pip install matplotlib spherical_geometry pycairo pygobject ipython

